AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "aws-xray-test"
      Handler: function.handler
      Runtime: ruby2.5
      CodeUri: code.zip
      Tracing: Active
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - dynamodb:ListTables
          Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*
